In [1]:
import numpy as np

In [2]:
%conda install imbalanced-learn

Solving environment: done

## Package Plan ##

  environment location: /DATA/souraviai/miniconda3/envs/M2m

  added / updated specs:
    - imbalanced-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    imbalanced-learn-0.10.1    |   py38h06a4308_0         277 KB
    joblib-1.1.1               |   py38h06a4308_0         382 KB
    scikit-learn-1.2.2         |   py38h6a678d5_0         7.7 MB
    threadpoolctl-2.2.0        |     pyh0d69192_0          16 KB
    ------------------------------------------------------------
                                           Total:         8.4 MB

The following NEW packages will be INSTALLED:

  imbalanced-learn   pkgs/main/linux-64::imbalanced-learn-0.10.1-py38h06a4308_0 
  joblib             pkgs/main/linux-64::joblib-1.1.1-py38h06a4308_0 
  scikit-learn       pkgs/main/linux-64::scikit-learn-1.2.2-py38h6a678d5_0 
  threadpoolctl      pkgs/main/no

In [2]:
from imblearn.metrics import geometric_mean_score, sensitivity_score

In [42]:
y = np.random.randint(10, size=500)
pred = np.random.randint(10, size=500)
# print(y)
# print(pred)
tmp1 = sensitivity_score(y, pred, average=None)
print(tmp1)
tmp2 = geometric_mean_score(y, pred)
print(tmp2)

[0.12195122 0.14       0.08695652 0.1        0.11538462 0.12765957
 0.18367347 0.16129032 0.04       0.04761905]
0.1021248208908909


In [4]:
acc = np.load("./logs/Imbalance_S320_M2m_L0.5_W160_E0.1_I10_svhn_R60_resnet32_G0.9_B0.999/classwise_acc.npy")
r =1 
for i in acc**(1/len(acc)):
    r *= i

print(r)

87.03538221022691


In [5]:
acc.mean()

87.25714

In [1]:
from torchvision import datasets

data = datasets.SUN397(root='./data', download=True)
# data = data.data / 255 # data is numpy array

# mean = data.mean(axis = (0,2,3)) 
# std = data.std(axis = (0,2,3))

RuntimeError: The daily quota of the file img_align_celeba.zip is exceeded and it can't be downloaded. This is a limitation of Google Drive and can only be overcome by trying again later.

In [26]:
print(np.round(mean, 4))
print(np.round(std, 4))

[0.4377 0.4438 0.4728]
[0.198 0.201 0.197]


In [23]:
mean

array([0.49139968, 0.48215841, 0.44653091])

In [10]:
data.labels

array([1, 9, 2, ..., 1, 6, 9])

In [2]:
import torch

In [5]:
p = torch.load("logs/Imb")

In [6]:
p['epoch']

159